### ISSUE TITLE
Possibly a bug with font imports with suffix "?#iefix"

### ISSUE THREAD

**Issue by samuelpismel** [torba-rb/torba#2]
Hey, I'm trying touse torba with Dogfalo/materialize, bug I'm getting an error on `torba pack`

The error message says:
```
Couldn't found an asset with path '/home/samuel/.torba/cache/materialize-9a4a2101/font/material-design-icons/Material-Design-Icons.eot?#iefix'.
Make sure that you've imported all image assets mentioned in a stylesheet(-s).
```

The file /home/samuel/.torba/cache/materialize-9a4a2101/font/material-design-icons/Material-Design-Icons.eot exists, but torba is trying to get the file with `?#iefi` suffix.

Is it a bug or am I doing something wrong?

Thanks!

**Comment by nashbridges** [comment]
Please, try v.0.3.1
Thanks for report!

**Comment by samuelpismel** [comment]
Wohoollll!!! Awesome!!!
Thanks!
