### ISSUE TITLE
Sprockets::ArgumentError: Asset logical path has no extension: angular/LICENSE

### ISSUE THREAD

**Issue by bhgames** [torba-rb/torba#21]
Hey guys, here's my setup:

Torbafile:
    `npm "requirejs", package: "requirejs", version: "2.1.22"

    npm "angular", package: "angular", version: "1.2.23"

    npm "angular-ordinal", package: "angular-ordinal", version: "2.1.3"

    npm "angular-route", package: "angular-route", version: "1.2.29" 

    npm "localforage", package: "localforage", version: "1.2.2"

    npm "angular-localforage", package: "angular-localforage", version: "1.2.5"

    gh_release "linkifyjs", source: "SoapBox/linkifyjs", tag: "v1.1.7"`

Here's my js file:
`    //= require 'angular/lib/angular.js'

    //= require 'angular-route/angular-route.js'

    //= require angular-rails-templates

    //= require 'localforage/dist/localforage.js'

    //= require 'angular-localforage/dist/angular-localForage.js'

    //= require 'angular-ordinal/ordinal-browser.js'

    //= require 'linkifyjs/dist/jquery.linkify.js'`

Ruby: 2.2.3
Rails: 4.2.5

Anyway, the error I get is:

    Sprockets::ArgumentError: Asset logical path has no extension: angular/LICENSE

when deploying to Heroku. I assume this is exactly what it says: This angular repository is now on the sprockets path and it has files without extensions in it. If you note above, I only include actual js in my code. I found this code on an old thread from Sprockets that might work, and I am going to experiment with it over the next couple days:

    # We don't want the default of everything that isn't js or css, because it pulls too many things in
    Rails.application.config.assets.precompile.shift

    # Explicitly register the extensions we are interested in compiling
    Rails.application.config.assets.precompile.push(Proc.new do |path|
        File.extname(path).in? [
          '.html', '.erb', '.haml',                 # Templates
          '.png',  '.gif', '.jpg', '.jpeg',         # Images
          '.eot',  '.otf', '.svc', '.woff', '.ttf', # Fonts
        ]
    end)

Which I got from:

https://github.com/sstephenson/sprockets/issues/347 Thanks @wadetandy

EDIT: It doesn't seem to work when I try it in application.rb, and the original code mentions initializer blocks which do not appear to exist in Rails 4. Going to keep on working on different variations. 

This is just an ongoing FYI for maybe to create a patch, or for others to find and know how to fix!

**Comment by mattbrictson** [comment]
Probably the "correct" solution is that you should explicitly import (i.e. whitelist) only the files from the angular package that you actually need. You can do this with the `:import` option [as explained in the README](https://github.com/torba-rb/torba#import-option).

Alternatively, as a patch, we could perhaps change the implementation of `Torba::ImportList#non_js_css_assets` to skip assets that are missing a file extension, since apparently Sprockets doesn't allow those.

https://github.com/torba-rb/torba/blob/0e33163b16375fe66fe0569d0fbc7e98a2224a97/lib/torba/import_list.rb#L46

**Comment by nashbridges** [comment]
Manual precompile option in Sprockets will eventually [become obsolete](https://github.com/sstephenson/sprockets/pull/639), therefore, I don't wan't to focus on it.

@bhgames, specify an "import" option as @mattbrictson explained. In your JS-only package case it should be as simple as `import: ["**/*.js"]`

**Comment by bhgames** [comment]
Ah ok, I remember reading that but I thought it was specifically only for CSS files. I'll re-read it and see if I can solve this.

**Comment by bhgames** [comment]
Ok, that worked, and I was able to deploy it to our Heroku staging.

Now I'm getting a weird Torba::Errors::MissingPackages error on CircleCi in the test env - well I was always getting it. I checked the ~/.torba directory and it's definitely getting filled. Gonna keep hacking at this, I'm close!

**Comment by bhgames** [comment]
Alright, got it to work in Circle. Issue was that I seemed to be installing the packages in a different user home directory than the server was being started in. Closing this. Thanks for all your help guys!
