### ISSUE TITLE
Capistrano precompiles :web only by default, leading to "Torba not packed" errors on other hosts

### ISSUE THREAD

**Issue by mattbrictson** [torba-rb/torba#23]
I ran into an unexpected problem today when deploying a Torba-enabled app to a multi-server environment using Capistrano.

By default, Capistrano only runs `assets:precompile` on hosts that have the `:web` role. This makes sense, because you typically only need assets when serving web requests. A background job worker that doesn't generate HTML, for example, doesn't need the asset pipeline.

However, Torba prevents the Rails process from booting if the Torbafile is not packed. So imagine my surprise when my Sidekiq processes (which load the Rails environment) on the worker hosts failed to start! Yikes.

The obvious workaround is to just run `assets:precompile` on *all* servers, which seems like a waste of resources.

I'm not sure if Torba itself can do anything about this, but it strikes me that Torba is making a big assumption that Rails will always be loaded in a web environment. That's not always the case.

**Comment by nashbridges** [comment]
As a temp workaround you can edit you Gemfile like this:

```ruby
group "web" do # or "assets"
  gem "torba", require: %w[torba/verify torba/rails]
end
```

and then bundle without this group in a non-web server.

For proper solution there should be a single point of entry for Torba, so we won't need to require an array. At least it should be "torba/rails", or even a separate gem should be extracted out. I prefer latter (no need to `require`), however, this would force a major version bump). 

The reason for separate require of "torba/verify" was only that Torba would fail fast (Rails boots up quite slow). If this complicates a project setup, this require should be made by library itself.

**Comment by nashbridges** [comment]
> I'm not sure if Torba itself can do anything about this

I couldn't think of any automatic solution since Rails itself has no notion of roles.

**Comment by mattbrictson** [comment]
OK, thanks for giving this some thought. I agree that there is nothing really Torba can do.
