### ISSUE TITLE
SCSS/SASS Variables

### ISSUE THREAD

**Issue by JanStevens** [torba-rb/torba#26]
Hello,

I'm having some issues with packages that contain scss variables. It seems that torba cannot really handle this, as example, add `font-awesome` or `bootstrap-sass` or `bourbon` to your Torba file and then run `rake assets:precompile`.

```ruby
npm package: 'font-awesome', version: '4.5.0',  import: %w(scss/)
```

```bash
 bundle exec rake assets:precompile
rake aborted!
Sass::SyntaxError: Undefined variable: "$fa-css-prefix".
/app/vendor/assets/.torba/font-awesome-e09190ff/font-awesome/_animated.scss:4
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```

Any help on this or is this expected?

**Comment by JanStevens** [comment]
Additional info:

```ruby
rails 4.5.2.1
sprockets 3.0.4
```

**Comment by nashbridges** [comment]
https://github.com/torba-rb/torba/commit/ec3543625b8ab50f39e35de6a3eea35d1e5a833d
Please, test v.0.5.1

**Comment by JanStevens** [comment]
Oke with `bourbon` I get the following very weird error:

```ruby
rake torba:pack
(in /app)
/app/vendor/assets/torba/cache/bourbon-d5af2033/app/assets/stylesheets/css3/image.png
Couldn't find an asset with path '/app/vendor/assets/torba/cache/bourbon-d5af2033/app/assets/stylesheets/css3/image.png'.
Make sure that you've imported all image/font assets mentioned in a stylesheet(-s).
```
A bit wierd because I don't have any `image.png` file at all.

I'm using the following code in my `Torbafile`:

```
npm package: 'bourbon', version: '4.2.6', import: %w(app/assets/stylesheets/)
```

**Comment by nashbridges** [comment]
Let's move to another issue, since last report has nothing with scss variables.
This seems to be fixed.

**Comment by JanStevens** [comment]
Hmm look at the bootstrap example that's a scss variable $path
