### ISSUE TITLE
bourbon: Couldn't find an asset with path

### ISSUE THREAD

**Issue by nashbridges** [torba-rb/torba#27]
From https://github.com/torba-rb/torba/issues/26#issuecomment-194391456:

> with bourbon I get the following very weird error:

```
rake torba:pack
(in /app)
/app/vendor/assets/torba/cache/bourbon-d5af2033/app/assets/stylesheets/css3/image.png
Couldn't find an asset with path '/app/vendor/assets/torba/cache/bourbon-d5af2033/app/assets/stylesheets/css3/image.png'.
Make sure that you've imported all image/font assets mentioned in a stylesheet(-s).
```

> A bit wierd because I don't have any image.png file at all.

> I'm using the following code in my Torbafile:

`npm package: 'bourbon', version: '4.2.6', import: %w(app/assets/stylesheets/)`

**Comment by nashbridges** [comment]
The issue caused by examples in css3/_border_image.scss:

```
//Examples:
// @include border-image(url("image.png"));
// @include border-image(url("image.png") 20 stretch);
```

I'm not sure how to correctly handle this.

It is a SCSS commentary, there's also a CSS multiline commentary. This could end up in a full featured CSS parser, which I want to avoid.

Would something like `ignore_asset` option be enough?

**Comment by JanStevens** [comment]
For this usecase it does 

But for bootstrap it will ignore the fonts right?

**Comment by nashbridges** [comment]
Please, let's not mix all issues into one.
I'll review (and hopefully fix) each issue one by one.
