### ISSUE TITLE
Allow to set the config in Torbafile

### ISSUE THREAD

**Issue by JanStevens** [torba-rb/torba#32]
Hello,

When using the new commands `show` and `info` I noticed that it didn't work for me since I changed the `Torba.home_path`, I had to prefix the commands with an ENV var.

Wouldn't it be better to set the config of `home_path` and `cache_path` in the `Torbafile` or somewhere else that is auto included? This way people don't have to remember the ENV variables.

For example Sidekiq can be configured using a sidekiq.yml file, allowing people just to run `bundle exec sidekiq` in the project dir and the correct settings would be used.

**Comment by nashbridges** [comment]
Could you describe you setup?
Why can't you just export env variables in your bash profile?

**Comment by JanStevens** [comment]
Since we have multiple projects and every dev has their own configuration / path to their projects. Exporting a ENV variable wont really work since a different project can save their assets in a different location.

We only commit `.example` yml files for example so every dev can arrange their structure / project how they like.

**Comment by nashbridges** [comment]
I don't understand why changing default Torba.home_path is necessary for that kind of setup. Actually Torba was designed to share assets between projects. Even if versions (or import list) are different, folders won't clash.

**Comment by JanStevens** [comment]
Ha oke, didn't knew that, so it's better to share the path between projects and lets torba figure out what to do with it

**Comment by nashbridges** [comment]
Exactly. Think of it like gems cached locally. You download rails-4.2.5.gem only once, then every project within a Ruby version will share it (Tim Pope even made possible to share gems across Rubies https://github.com/tpope/rbenv-communal-gems)

**Comment by nashbridges** [comment]
Closing this. Feel free to reopen it if you still have problems.
