### ISSUE TITLE
Loading daemon fails because of not finding Torbafile

### ISSUE THREAD

**Issue by onlinetocode** [torba-rb/torba#33]
Hi there,

torba is really a great gem! I discovered it through Jan Stevens blog post on fritz.ninja and am now a big fan of torba!

But today I ran into this issue. I have a mailman server which is daemonized via the daemon gem.

Since I integrated torba I found that the daemon doesn't load anymore.

It fails with this:

```
mailman_server: process with pid 47924 started.
/Users/user/.rvm/gems/ruby-2.2.2@app_production_gemset/gems/torba-0.7.0/lib/torba/manifest.rb:36:in `read': No such file or directory @ rb_sysopen - /Torbafile (Errno::ENOENT)
	from /Users/user/.rvm/gems/ruby-2.2.2@app_production_gemset/gems/torba-0.7.0/lib/torba/manifest.rb:36:in `build'
	from /Users/user/.rvm/gems/ruby-2.2.2@app_production_gemset/gems/torba-0.7.0/lib/torba.rb:48:in `manifest'
	from /Users/user/.rvm/gems/ruby-2.2.2@app_production_gemset/gems/torba-0.7.0/lib/torba.rb:69:in `verify'
	from /Users/user/.rvm/gems/ruby-2.2.2@app_production_gemset/gems/torba-0.7.0/lib/torba/verify.rb:12:in `<top (required)>'
	from /Users/user/rails/app_backend/config/boot.rb:7:in `require'
	from /Users/user/rails/app_backend/config/boot.rb:7:in `<top (required)>'
	from /Users/user/rails/app_backend/config/application.rb:1:in `require'
	from /Users/user/rails/app_backend/config/application.rb:1:in `<top (required)>'
	from /Users/user/rails/app_backend/config/environment.rb:3:in `require'
	from /Users/user/rails/app_backend/config/environment.rb:3:in `<top (required)>'
	from /Users/user/rails/app_backend/script/mailman_server:5:in `require'
	from /Users/user/rails/app_backend/script/mailman_server:5:in `<top (required)>'
	from /Users/user/.rvm/gems/ruby-2.2.2@app_production_gemset/gems/daemons-1.2.3/lib/daemons/application.rb:218:in `load'
	from /Users/user/.rvm/gems/ruby-2.2.2@app_production_gemset/gems/daemons-1.2.3/lib/daemons/application.rb:218:in `start_load'
	from /Users/user/.rvm/gems/ruby-2.2.2@app_production_gemset/gems/daemons-1.2.3/lib/daemons/application.rb:297:in `start'
	from /Users/user/.rvm/gems/ruby-2.2.2@app_production_gemset/gems/daemons-1.2.3/lib/daemons/controller.rb:56:in `run'
	from /Users/user/.rvm/gems/ruby-2.2.2@app_production_gemset/gems/daemons-1.2.3/lib/daemons.rb:144:in `block in run'
	from /Users/user/.rvm/gems/ruby-2.2.2@app_production_gemset/gems/daemons-1.2.3/lib/daemons/cmdline.rb:88:in `call'
	from /Users/user/.rvm/gems/ruby-2.2.2@app_production_gemset/gems/daemons-1.2.3/lib/daemons/cmdline.rb:88:in `catch_exceptions'
	from /Users/user/.rvm/gems/ruby-2.2.2@app_production_gemset/gems/daemons-1.2.3/lib/daemons.rb:143:in `run'
	from script/mailman_daemon:19:in `<main>'
```

I start the daemon with this command: RAILS_ENV=development bundle exec script/mailman_daemon start.

It seems to me that it fails because Torba searches the mainfest file with 

```ruby
    def self.build(file_path = ENV["TORBA_FILE"])
      file_path ||= File.join(Dir.pwd, "Torbafile")

      manifest = new
      content = File.read(file_path)
      manifest.instance_eval(content, file_path)
      manifest
    end
```

in the `lib/torba/manifest.rb` at line 33 and obviously fails because Dir.pwd returns the script directory as the the current working directory of this daemon process instead of the root directory.

I could fix this on my side through integrating

```ruby
ENV["TORBA_FILE"] = File.join(Dir.pwd, "Torbafile")
```

in my daemon file under `script/mailman_daemon`.

Because of the use of `Dir.pwd` it should fail everytime when the call's origin isn't the rails root directory. Maybe there is another way to specify the default Torbafile path.

Best
Maurice

**Comment by nashbridges** [comment]
Why do you think that specifying `TORBA_FILE` is a bad idea? It seems pretty reasonable for me, since other options like `Torba.home_path` and `Torba.cache_path` could be also defined via env variables.

You can also `cd` into project root before executing the script.

I really don't want to complicate the project by introducing complex lookup logic, like Rake or Bundler do.

**Comment by nashbridges** [comment]
Although the main issue here is that your mail daemon doesn't need Torba at all (see https://github.com/torba-rb/torba/issues/23 as another example).

I was thinking to disable Torba in production by default (except assets task), but you run your daemon with `RAILS_ENV=development`. Could you explain the reason?

**Comment by onlinetocode** [comment]
I don't think that it is a bad idea. It works perfect for me. But it took me a whole afternoon to find the reason for it and fix the failing startup of my mailer daemon. 

I think of the intuitivness in using this library. torba is really such a cool gem which definitly should have a place in most of the Gemfiles out there ;)

But I can think of other less to mid experienced developers running into similar problems which are not that easy to debug for some of them (like me as well). It would be a shame if people are stopping using torba because they ran into such kinds of problem.

I run the daemon in development because I fixed this problem in development environment on my local machine after I discovered the problem on my production system.

Actually I execute the script from my project root, but the daemon starts the mailman script out of the `/script` directory. Therefore the manifest lookup starts from the `/script` directory.

Maybe that is really a very uncommon problem which could be handled by an entry in the README with a reference to the ENV variables of torba. But if such a problem could happen more often and in other cases that should be handled somehow for the well-being of this gem. 

I read about your thoughts to extract a seperate torba-rails gem out of torba. I think that could be very useful for torba and it's adoption because such cases like mine could be better handled when the general environment is the same and you could always count on the typical rails file structure.

Could you confirm that with using something like

```ruby
group "web" do # or "assets" ?
  gem "torba", require: %w[torba/verify torba/rails]
end
```
in my Gemfile it would be unnecessary to require torba in my `boot.rb` and in my `application.rb`?

It is true that I don't need torba to start my mailman server. So disabeling torba in production could be a solution as well for a stumbling block like mine. 

To make sure I will keep using torba and fight through such rare cases because it is a damn good gem!

**Comment by nashbridges** [comment]
I agree that the error should be more specific than generic "file not found".



> it would be unnecessary to require torba in my boot.rb and in my application.rb?

Exactly. You should remove both requirements in that case.



> extract a seperate torba-rails gem

Yes, it is in my todo list.

**Comment by nashbridges** [comment]
> extract a seperate torba-rails gem

and done https://github.com/torba-rb/torba-rails
