### ISSUE TITLE
Using with Sinatra. Coming from RailsAssets

### ISSUE THREAD

**Issue by xfalcox** [torba-rb/torba#34]
Hello, awesome gem!

I'm trying to migrate my Sinatra workflow using rails-assets to torba, but no dice yet.

I use this workflow, that works very well on development and on production: https://github.com/xfalcox/sinatra-assets-seed

Having a hard time finding the assets on my sinatra app.

**Comment by xfalcox** [comment]
Nevermind, just did it and update the repo. :fireworks:

**Comment by nashbridges** [comment]
Great!
Have you considered using https://github.com/kalasjocke/sinatra-asset-pipeline ?

**Comment by xfalcox** [comment]
Yeah, but this project has no support for latest Sinatra (1.4.7), no support for sprockets > 3  and no relative root. 

My seed gives me all that.
