### ISSUE TITLE
Is there any ability to use torba on Heroku?

### ISSUE THREAD

**Issue by timurkhafizov** [torba-rb/torba#4]

**Comment by nashbridges** [comment]
I believe, you can with https://devcenter.heroku.com/articles/buildpack-api (by forking default ruby buildpack). Would be great if you try it out and contribute to README.

**Comment by mattbrictson** [comment]
Perhaps an alternative would be to introduce a "vendored" mode where Torba would pack the dependencies within the project, e.g. in `vendor/torba`. Then you could commit those to source control and deploy to Heroku without needing a custom buildpack.

**Comment by nashbridges** [comment]
There's [another discussion](https://github.com/heroku/heroku-buildpack-ruby/issues/442) with [Rake task override](https://github.com/heroku/heroku-buildpack-ruby/issues/442#issuecomment-164174721) approach/hack. I didn't have time so far to test that.

**Comment by mattbrictson** [comment]
Great idea, thanks. It would be neat if Torba shipped with a Rake task that adds `torba pack` as a prerequisite to the Rails `assets:precompile`. Then deployments would "just work", on Herkou or anywhere, really.

Installation would be something like this:

```ruby
# In Rakefile
Rails.application.load_tasks
require "torba/rake_task"
Torba::RakeTask.new("assets:precompile")
```

Would you consider accepting a PR along these lines?

**Comment by nashbridges** [comment]
Sure. Your idea for adding task as a dependency instead of overriding is even better. Just make sure it really works on a Heroku project.

**Comment by nashbridges** [comment]
Another important thing is that `Torba.home_path` should be set to [CACHE_DIR](https://devcenter.heroku.com/articles/buildpack-api) on Heroku. That way we will pack assets only once.

**Comment by mattbrictson** [comment]
@nashbridges Correct me if I'm wrong, but it seems like I would have no access to the CACHE_DIR value from within the Rake task. The only way to get this value is to customize the buildpack itself, since it is passed in as an argument to `bin/compile`.

The only option that I see is to have Torba use `tmp/cache/assets`, since that is a directory that the Ruby buildpack already stores in the CACHE_DIR.

Do you think there would be problems/collisions if Torba and Sprockets share the same cache directory?

Or if you can think of any other way to access the CACHE_DIR value without customizing the buildpack, let me know!

**Comment by mattbrictson** [comment]
Perhaps if I set `Torba.home_path` to `tmp/cache/assets/_torba` that will be safe enough?

**Comment by nashbridges** [comment]
Will [ARGV](https://github.com/heroku/heroku-buildpack-ruby/blob/master/bin/compile#L12) be different at that time?

**Comment by mattbrictson** [comment]
I believe so, because ARGV will be set based on what was passed to `rake assets:precompile`, not what was given to `bin/compile`.

**Comment by mattbrictson** [comment]
Actually, it looks like the Rake task is run in-process rather than shelling out. So ARGV might still work. Thanks! I'll give that a shot.

**Comment by mattbrictson** [comment]
Ah, never mind. Rake *is* invoked via shell: https://github.com/heroku/heroku-buildpack-ruby/blob/master/lib/language_pack/helpers/rake_runner.rb#L47. So I think the ARGV option won't work. I'll still try it just in case.
