### ISSUE TITLE
It seems it can't handle npm names like `@lottiefiles/lottie-player`

### ISSUE THREAD

**Issue by aTei** [torba-rb/torba#42]
https://www.npmjs.com/package/@lottiefiles/lottie-player

It tries to get package from 
https://registry.npmjs.org/@lottiefiles/lottie-player/-/@lottiefiles/lottie-player-2.0.2.tgz

Correct url would be
https://registry.npmjs.org/@lottiefiles/lottie-player/-/lottie-player-2.0.2.tgz

**Comment by nashbridges** [comment]
Thanks for reporting!
In the meantime please use the [tgz declaration](https://github.com/torba-rb/torba#targz-archive-package) which allows to specify full URL.
